### PR TITLE
Add order attribute to Preselection element

### PR DESCRIPTION
**Pull request by sdp198**
Adding order attribute with new type PreselectionOrderType to the Preselection element.  Aee 5.3.11.4 of 4th edition text.

### CODE REVIEW

**Comment by mikedo** [comment]
Thanks.  I've commented in the document about the use of integer for this versus enum of tokens.

**Comment by sdp198** [comment]
I thought it seemed an odd choice.

**Comment by paulhiggs** [comment]
I don't see any good reason to express enumerations of values as integers. It just makes readability more complex when you see <something order="0">then you have to go and read the spec for the clarification of "0". Its better just to say <something order="first"> if that is what it is
We are not trying to stuff values into serialized bitstreams!

**Comment by sdp198** [comment]
I've changed it o be an enum with the following values:

- unordered
- time-ordered
- fully-ordered

I was expecting it to result in a new pull request, but it conveniently seems to have just updated this one.

**Pull request merged**
