### PR TITLE
4th-Ed

### PR DESCRIPTION
**Pull request by mikedo**

### CODE REVIEW

**Comment by paulhiggs** [comment]
The change for example_G8 includes a namespace definition for drm: (`  xmlns:drm="http://example.net/052011/drm"`) but this is not used in the example. Better to remove it than lead to any uncertainty.

**Comment by sdp198** [comment]
This looks like it's going to add the changes from Amd5 directly into the 3rd edition branch.  I think the intention may have been to make a new branch called 4th edition, and then merge in the AMD 5 branch?

**Comment by mikedo** [comment]
Yes, 3rd Ed should remain as published.  We probably need a 4th Ed branch, at least temporarily. But I'm scratching my head now about how best to proceed with the work to date and pushing the latest work into the master which is what others might expect.

**Comment by paulhiggs** [comment]
The use of Github and 'master' depends entirely on what we want to be the purpose of the tool and its authority.
a) If this repository is used for specification development, then 4th Ed updates should me merged into master, then tagged/branced when published.
b) If this repository is to be the authoritative reference then 4th Ed updates should be made on a branch and only merged into master when the standard is completed and published.

I would propose a) - this repository is for standard development only. Its "latest" state reflects the current progress of the related specification

**Comment by mikedo** [comment]
The authoritative files after publication are (e.g. for 3rd Ed) now posted here: https://standards.iso.org/iso-iec/23009/-1/ed-3/en   Average users of the standard would not see/know about github. So, I also think it is (a).

**Comment by mikedo** [comment]
Overtaken by recent events

**Pull request closed without merging**
