### PR TITLE
Update DASH-MPD.xsd per Issue 55

### PR DESCRIPTION
**Pull request by mikedo**
See Issue #55

### CODE REVIEW

**Comment by paulhiggs** [comment]
I would suggest that we stop using general comments `<!--  comment -->` and use the formal syntax
````
<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.w3.org/XML/2008/06/xlink.xsd">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      xlink import. URL is per https://www.w3.org/TR/xlink/  
      Users are encouraged to store a local copy
    </xs:documentation>
  </xs:annotation>
</xs:import>
````

**Comment by mikedo** [comment]
Sure, especially for this.  I'm less excited about converting all of the existing inline comments, but feel free to produce a PR converting them all :-)

**Comment by mikedo** [comment]
@paulhiggs Can you open a new issue with the general annotation comment above? I still agree but with the short deadline to get a matching schema out today, I'd like to defer any editorial changes for risk of breaking something. Thanks.

**Comment by paulhiggs** [comment]
Done, see issue #71

**Pull request merged**
